// Nearly V1 - Mpumalanga Province Dataset
// Primary Base Province: Mpumalanga, South Africa
// Key Hubs: Mbombela (Nelspruit), eMalahleni (Witbank), Middelburg, Secunda, White River, Barberton, Hazyview, Ermelo, Standerton, Lydenburg

const AVAILABLE_AREAS = [
  "Mbombela (Nelspruit), Mpumalanga",
  "eMalahleni (Witbank), Mpumalanga",
  "Middelburg, Mpumalanga",
  "Secunda, Mpumalanga",
  "White River, Mpumalanga",
  "Barberton, Mpumalanga",
  "Hazyview, Mpumalanga",
  "Ermelo, Mpumalanga",
  "Standerton, Mpumalanga",
  "Lydenburg (Mashishing), Mpumalanga"
];

const CITY_COORDINATES = {
  "Mbombela (Nelspruit), Mpumalanga": { lat: -25.4753, lng: 30.9694 },
  "eMalahleni (Witbank), Mpumalanga": { lat: -25.8744, lng: 29.2332 },
  "Middelburg, Mpumalanga": { lat: -25.7711, lng: 29.4608 },
  "Secunda, Mpumalanga": { lat: -26.5143, lng: 29.1795 },
  "White River, Mpumalanga": { lat: -25.3322, lng: 31.0116 },
  "Barberton, Mpumalanga": { lat: -25.7884, lng: 31.0532 },
  "Hazyview, Mpumalanga": { lat: -25.0441, lng: 31.1278 },
  "Ermelo, Mpumalanga": { lat: -26.5333, lng: 29.9833 },
  "Standerton, Mpumalanga": { lat: -26.9333, lng: 29.2417 },
  "Lydenburg (Mashishing), Mpumalanga": { lat: -25.0961, lng: 30.4600 }
};

const CATEGORIES = [
  { id: "Food", name: "Food", icon: "utensils", color: "#E11D48" },
  { id: "Shopping", name: "Shopping", icon: "shopping-bag", color: "#D97706" },
  { id: "Services", name: "Services", icon: "wrench", color: "#0284C7" },
  { id: "Repairs", name: "Repairs", icon: "tools", color: "#7C3AED" },
  { id: "Transport", name: "Transport", icon: "bus", color: "#059669" },
  { id: "Health", name: "Health", icon: "heart-pulse", color: "#DC2626" },
  { id: "Education", name: "Education", icon: "graduation-cap", color: "#4338CA" },
  { id: "Printing", name: "Printing", icon: "print", color: "#0D9488" },
  { id: "Beauty", name: "Beauty", icon: "scissors", color: "#DB2777" },
  { id: "Electronics", name: "Electronics", icon: "laptop", color: "#2563EB" },
  { id: "Other", name: "Other", icon: "th-large", color: "#64748B" }
];

const PLACES_DATA = [
  // ELECTRONICS - MBOMBELA & MPUMALANGA
  {
    id: "elec-mbombela-1",
    name: "Matrix Warehouse Nelspruit",
    category: "Electronics",
    description: "Computer components, phone chargers, USB-C cables, power banks, adapters, monitors, and gaming gear.",
    address: "Shop LG08, Ilanga Mall, Bitterbessie St, West Acres, Mbombela",
    area: "Mbombela (Nelspruit), Mpumalanga",
    baseDistance: 0.4,
    phone: "+27 13 742 2291",
    latitude: -25.4678,
    longitude: 30.9575,
    openingHours: "Mon-Sat: 09:00 - 18:00, Sun: 09:00 - 17:00",
    isOpen: true,
    rating: 4.8,
    reviews: 186,
    tags: ["phone charger", "type-c", "charger", "fast charger", "power bank", "usb cable", "iphone cable", "adapter", "laptop", "lowveld electronics"],
    services: ["Fast charging adapters", "Braided USB-C & Lightning cables", "Laptop power bricks", "Power banks", "Screen protector fitting"]
  },
  {
    id: "elec-mbombela-2",
    name: "Incredible Connection Riverside",
    category: "Electronics",
    description: "Smartphones, genuine Apple & Samsung fast chargers, wireless charging stations, tech accessories, and headphones.",
    address: "Shop 32, Riverside Mall, Government Blvd, Riverside Park, Mbombela",
    area: "Mbombela (Nelspruit), Mpumalanga",
    baseDistance: 0.8,
    phone: "+27 13 757 0440",
    latitude: -25.4372,
    longitude: 30.9691,
    openingHours: "Mon-Sat: 09:00 - 19:00, Sun: 09:00 - 17:00",
    isOpen: true,
    rating: 4.7,
    reviews: 240,
    tags: ["phone charger", "magsafe", "samsung charger", "apple charger", "headphones", "bluetooth", "gadgets", "riverside mall"],
    services: ["Certified smartphone chargers", "Official warranty accessories", "Bluetooth speakers", "Smart home devices"]
  },
  {
    id: "elec-witbank-1",
    name: "Cell Clinic & Tech Gadgets eMalahleni",
    category: "Electronics",
    description: "High-speed multi-port chargers, car chargers, power banks, Bluetooth audio, and accessories for all smartphone models.",
    address: "Saveways Crescent Centre, OR Tambo Rd, eMalahleni",
    area: "eMalahleni (Witbank), Mpumalanga",
    baseDistance: 0.5,
    phone: "+27 13 656 2210",
    latitude: -25.8712,
    longitude: 29.2390,
    openingHours: "Mon-Fri: 08:30 - 17:30, Sat: 09:00 - 14:00",
    isOpen: true,
    rating: 4.5,
    reviews: 92,
    tags: ["phone charger", "fast charger", "car charger", "power bank", "witbank", "emalahleni", "charger"],
    services: ["Dual-port fast chargers", "Car 12V adapters", "Tempered glass screen guards", "Heavy-duty charging cables"]
  },
  {
    id: "elec-secunda-1",
    name: "Secunda Tech & Mobile Hub",
    category: "Electronics",
    description: "Comprehensive smartphone accessories, replacement batteries, chargers, cables, and wireless audio.",
    address: "Shop G24, Secunda Mall, PDP Kruger St, Secunda",
    area: "Secunda, Mpumalanga",
    baseDistance: 0.6,
    phone: "+27 17 634 8100",
    latitude: -26.5160,
    longitude: 29.1780,
    openingHours: "Mon-Sat: 09:00 - 18:00, Sun: 09:00 - 15:00",
    isOpen: true,
    rating: 4.6,
    reviews: 110,
    tags: ["phone charger", "secunda charger", "cables", "power bank", "secunda mall", "gadgets"],
    services: ["Same-day charger replacements", "Wireless power banks", "Earphones & audio plugs"]
  },

  // PRINTING - MBOMBELA & MPUMALANGA
  {
    id: "print-mbombela-1",
    name: "PostNet Nelspruit Crossing",
    category: "Printing",
    description: "Full document printing, color photocopying, laminating, wire binding, scanning to email, courier, and passport photos.",
    address: "Shop 12, Crossing Shopping Centre, Cnr Madiba Dr & Samora Machel Dr, Mbombela",
    area: "Mbombela (Nelspruit), Mpumalanga",
    baseDistance: 0.5,
    phone: "+27 13 752 8225",
    latitude: -25.4740,
    longitude: 30.9680,
    openingHours: "Mon-Fri: 08:00 - 17:30, Sat: 08:30 - 13:00",
    isOpen: true,
    rating: 4.7,
    reviews: 175,
    tags: ["print", "printing", "print documents", "documents", "copies", "photocopy", "laminating", "binding", "scan", "postnet nelspruit", "cv", "resume"],
    services: ["A4/A3 color & B/W printing", "Document laminating & spiral binding", "Scan documents to email/USB", "Domestic & international courier"]
  },
  {
    id: "print-mbombela-2",
    name: "Jetline Print & Design Mbombela",
    category: "Printing",
    description: "Commercial digital printing, business cards, large architectural plan printing, banners, flyers, and booklets.",
    address: "22 Henshall St, Mbombela CBD, Mbombela",
    area: "Mbombela (Nelspruit), Mpumalanga",
    baseDistance: 0.9,
    phone: "+27 13 752 4433",
    latitude: -25.4715,
    longitude: 30.9750,
    openingHours: "Mon-Fri: 08:00 - 17:00, Sat: Closed",
    isOpen: false,
    rating: 4.6,
    reviews: 88,
    tags: ["print documents", "large format printing", "business cards", "flyers", "blueprints", "banners", "jetline mbombela"],
    services: ["Architectural plan prints", "Brochures & annual reports", "Pull-up banners", "Same-day rush document printing"]
  },
  {
    id: "print-witbank-1",
    name: "3@1 Business Centre Highveld Mall",
    category: "Printing",
    description: "Document printing, color copies, resume printing, internet cafe station, laminating, and courier services.",
    address: "Shop 48, Highveld Mall, Mandela St, eMalahleni",
    area: "eMalahleni (Witbank), Mpumalanga",
    baseDistance: 0.3,
    phone: "+27 13 692 7331",
    latitude: -25.8750,
    longitude: 29.2320,
    openingHours: "Mon-Fri: 08:00 - 17:30, Sat: 08:30 - 13:00",
    isOpen: true,
    rating: 4.4,
    reviews: 95,
    tags: ["print documents", "internet cafe", "copies", "laminating", "witbank printing", "print cv"],
    services: ["Walk-in USB printing", "Certificate laminating", "Internet workstation", "Courier counter"]
  },

  // REPAIRS - MBOMBELA & MPUMALANGA
  {
    id: "rep-mbombela-1",
    name: "Dr. Phone Fix Lowveld",
    category: "Repairs",
    description: "Fast, professional phone repair. Screen replacement in 30 minutes, charging port repair, water damage diagnostics, and battery swap.",
    address: "32 Bester St, Mbombela CBD, Mbombela",
    area: "Mbombela (Nelspruit), Mpumalanga",
    baseDistance: 0.6,
    phone: "+27 82 555 4910",
    latitude: -25.4735,
    longitude: 30.9730,
    openingHours: "Mon-Sat: 08:30 - 18:00",
    isOpen: true,
    rating: 4.9,
    reviews: 275,
    tags: ["fix phone", "phone repair", "screen fix", "cracked screen", "battery replacement", "charging port", "water damage", "samsung fix", "iphone fix", "dr phone fix"],
    services: ["Screen replacement in 30 mins", "Battery swap with warranty", "Charging port cleaning & replacement", "Speaker and microphone repair"]
  },
  {
    id: "rep-mbombela-2",
    name: "iRepair Lowveld & Laptop Clinic",
    category: "Repairs",
    description: "Apple iPhone, iPad, MacBook & Windows laptop repairs, logic board repair, data recovery, and genuine display replacements.",
    address: "Shop 18, Valley Hyper Centre, Samora Machel Dr, Mbombela",
    area: "Mbombela (Nelspruit), Mpumalanga",
    baseDistance: 1.1,
    phone: "+27 13 755 1200",
    latitude: -25.4760,
    longitude: 30.9630,
    openingHours: "Mon-Fri: 08:30 - 17:30, Sat: 09:00 - 14:00",
    isOpen: true,
    rating: 4.8,
    reviews: 145,
    tags: ["phone repair", "macbook repair", "laptop repair", "cracked screen", "iphone screen", "tablet repair", "irepair lowveld"],
    services: ["MacBook screen & battery service", "Diagnostic testing", "Water damage ultrasonic cleaning", "Microsoldering"]
  },

  // BEAUTY - MBOMBELA & MPUMALANGA
  {
    id: "bea-mbombela-1",
    name: "Legends Barbershop Ilanga Mall",
    category: "Beauty",
    description: "Premier modern barbershop. Sharp skin fades, beard sculpting, hot towel grooming, hair design, and head massages.",
    address: "Shop 62, Ilanga Mall, Bitterbessie St, Mbombela",
    area: "Mbombela (Nelspruit), Mpumalanga",
    baseDistance: 0.4,
    phone: "+27 13 742 2110",
    latitude: -25.4675,
    longitude: 30.9570,
    openingHours: "Mon-Sat: 08:30 - 19:00, Sun: 09:00 - 17:00",
    isOpen: true,
    rating: 4.9,
    reviews: 380,
    tags: ["barber", "haircut", "fade", "beard", "haircut nearby", "shave", "legends barbershop", "grooming", "mbombela barber"],
    services: ["Signature skin fade", "Beard oil treatment & razor outline", "Kids cuts", "VIP head wash & massage"]
  },
  {
    id: "bea-mbombela-2",
    name: "Sorbet Salon Riverside Mall",
    category: "Beauty",
    description: "Full service beauty salon: manicures, gel pedicures, soothing facials, waxing, tinting, and relaxing massage therapy.",
    address: "Shop 54, Riverside Mall, Government Blvd, Mbombela",
    area: "Mbombela (Nelspruit), Mpumalanga",
    baseDistance: 0.8,
    phone: "+27 13 757 0820",
    latitude: -25.4370,
    longitude: 30.9695,
    openingHours: "Mon-Sat: 09:00 - 18:00, Sun: 09:00 - 17:00",
    isOpen: true,
    rating: 4.7,
    reviews: 190,
    tags: ["salon", "nails", "manicure", "pedicure", "massage", "waxing", "facial", "sorbet riverside"],
    services: ["Gelish nails & pedicures", "Dermalogica facial treatments", "Hot stone massage", "Eyebrow threading & tint"]
  },
  {
    id: "bea-whiteriver-1",
    name: "Lowveld Cuts & Shave Lounge",
    category: "Beauty",
    description: "Classic scissor styling, tapers, beard trims, and hot towel pampering in relaxed Lowveld surroundings.",
    address: "Casterbridge Lifestyle Centre, R40, White River",
    area: "White River, Mpumalanga",
    baseDistance: 0.5,
    phone: "+27 13 750 1900",
    latitude: -25.3340,
    longitude: 31.0130,
    openingHours: "Mon-Sat: 08:30 - 17:30, Sun: 09:00 - 14:00",
    isOpen: true,
    rating: 4.8,
    reviews: 125,
    tags: ["barber", "white river barber", "haircut", "beard trim", "shave"],
    services: ["Scissor cut & style", "Beard trim & conditioning", "Traditional straight razor shave"]
  },

  // EDUCATION - MBOMBELA & MPUMALANGA
  {
    id: "edu-mbombela-1",
    name: "PNA Nelspruit Crossing",
    category: "Education",
    description: "Complete school stationery, academic books, backpacks, Casio scientific calculators, art supplies, and notebooks.",
    address: "Shop 16, Crossing Shopping Centre, Madiba Dr, Mbombela",
    area: "Mbombela (Nelspruit), Mpumalanga",
    baseDistance: 0.5,
    phone: "+27 13 752 2788",
    latitude: -25.4745,
    longitude: 30.9685,
    openingHours: "Mon-Fri: 08:30 - 17:30, Sat: 08:30 - 15:00, Sun: 09:00 - 13:00",
    isOpen: true,
    rating: 4.7,
    reviews: 210,
    tags: ["school supplies", "stationery", "school shoes", "textbooks", "calculators", "pens", "notebooks", "pna nelspruit"],
    services: ["Back to school pack assembly", "Art & craft materials", "Office supplies & printing paper", "Scientific calculators"]
  },
  {
    id: "edu-mbombela-2",
    name: "Exclusive Books Riverside",
    category: "Education",
    description: "Vast selection of literature, non-fiction, business, children's books, Moleskine notebooks, and fine stationery.",
    address: "Shop 42, Riverside Mall, Government Blvd, Mbombela",
    area: "Mbombela (Nelspruit), Mpumalanga",
    baseDistance: 0.8,
    phone: "+27 13 757 0280",
    latitude: -25.4375,
    longitude: 30.9690,
    openingHours: "Mon-Sat: 09:00 - 19:00, Sun: 09:00 - 17:00",
    isOpen: true,
    rating: 4.8,
    reviews: 310,
    tags: ["books", "exclusive books", "novels", "reading", "stationery", "journal"],
    services: ["Special book orders", "Gift wrapping", "Children's storybooks"]
  },

  // HEALTH - MBOMBELA & MPUMALANGA
  {
    id: "hea-mbombela-1",
    name: "Clicks Pharmacy Ilanga Mall",
    category: "Health",
    description: "Prescription medicines, flu & allergy treatments, wellness clinic, blood pressure checks, baby clinic, and vitamins.",
    address: "Shop 38, Ilanga Mall, Bitterbessie St, Mbombela",
    area: "Mbombela (Nelspruit), Mpumalanga",
    baseDistance: 0.4,
    phone: "+27 13 742 2250",
    latitude: -25.4670,
    longitude: 30.9572,
    openingHours: "Mon-Sat: 08:30 - 19:00, Sun: 09:00 - 17:00",
    isOpen: true,
    rating: 4.6,
    reviews: 290,
    tags: ["pharmacy", "medicine", "headache", "flu", "pills", "clicks ilanga", "clinic", "vitamins", "first aid"],
    services: ["Prescription dispensary", "Blood pressure & glucose screening", "Flu vaccines", "Baby immunizations"]
  },
  {
    id: "hea-mbombela-2",
    name: "Mediclinic Nelspruit Hospital Pharmacy",
    category: "Health",
    description: "24-Hour emergency hospital dispensary, acute medical supplies, specialized prescription drugs, and wound care.",
    address: "1 Louise St, Sonheuwel, Mbombela",
    area: "Mbombela (Nelspruit), Mpumalanga",
    baseDistance: 1.2,
    phone: "+27 13 759 0500",
    latitude: -25.4850,
    longitude: 30.9680,
    openingHours: "Open 24 Hours / 7 Days",
    isOpen: true,
    rating: 4.7,
    reviews: 410,
    tags: ["hospital", "pharmacy", "doctor", "emergency", "mediclinic nelspruit", "24 hours", "medicine"],
    services: ["24/7 Emergency medicine", "Discharge prescriptions", "Specialist consultations", "Wound care supplies"]
  },

  // FOOD - MBOMBELA & MPUMALANGA
  {
    id: "foo-mbombela-1",
    name: "The Greek Kouzina Riverside",
    category: "Food",
    description: "Authentic Mediterranean dining, succulent lamb chops, fresh seafood, meze platters, and gourmet lunches overlooking the dam.",
    address: "Riverside Mall Promenade, Government Blvd, Mbombela",
    area: "Mbombela (Nelspruit), Mpumalanga",
    baseDistance: 0.8,
    phone: "+27 13 757 0212",
    latitude: -25.4378,
    longitude: 30.9692,
    openingHours: "Mon-Sun: 11:30 - 22:00",
    isOpen: true,
    rating: 4.8,
    reviews: 540,
    tags: ["food", "restaurant", "lunch", "dinner", "greek kouzina", "seafood", "riverside dining"],
    services: ["Sit-down dining with view", "Takeaway orders", "Private event bookings", "Cocktail bar"]
  },
  {
    id: "foo-mbombela-2",
    name: "Woolworths Food Ilanga Mall",
    category: "Food",
    description: "Fresh groceries, organic produce, hot rotisserie chicken, artisan bakery, specialty cheese, and coffee bar.",
    address: "Ilanga Mall, Bitterbessie St, Mbombela",
    area: "Mbombela (Nelspruit), Mpumalanga",
    baseDistance: 0.4,
    phone: "+27 13 742 2200",
    latitude: -25.4672,
    longitude: 30.9578,
    openingHours: "Mon-Sun: 08:00 - 20:00",
    isOpen: true,
    rating: 4.8,
    reviews: 460,
    tags: ["groceries", "supermarket", "food", "dinner", "lunch", "woolworths nelspruit", "fresh produce", "bakery", "bread", "milk"],
    services: ["Fresh hot deli counter", "Artisan sourdough bakery", "Organic fruits & veggies", "Specialty coffee bar"]
  },
  {
    id: "foo-whiteriver-1",
    name: "Magnolia Restaurant & Cafe",
    category: "Food",
    description: "French-inspired bistro and country cafe nestled in White River, serving artisanal breakfasts, cakes, and seasonal lunches.",
    address: "Casterbridge Lifestyle Centre, R40, White River",
    area: "White River, Mpumalanga",
    baseDistance: 0.5,
    phone: "+27 13 751 1947",
    latitude: -25.3345,
    longitude: 31.0135,
    openingHours: "Mon-Sat: 07:30 - 21:00, Sun: 07:30 - 17:00",
    isOpen: true,
    rating: 4.9,
    reviews: 380,
    tags: ["food", "cafe", "coffee", "breakfast", "lunch", "white river restaurant", "magnolia"],
    services: ["Garden terrace dining", "Freshly baked pastries", "Craft coffee & wine selection"]
  },

  // SHOPPING - MBOMBELA & MPUMALANGA
  {
    id: "sho-mbombela-1",
    name: "Riverside Mall Shopping Hub",
    category: "Shopping",
    description: "Mpumalanga's largest shopping destination with over 140 stores, major department retailers, fashion, and cinemas.",
    address: "Government Blvd, Riverside Park, Mbombela",
    area: "Mbombela (Nelspruit), Mpumalanga",
    baseDistance: 0.8,
    phone: "+27 13 757 0080",
    latitude: -25.4370,
    longitude: 30.9690,
    openingHours: "Mon-Sat: 09:00 - 19:00, Sun: 09:00 - 17:00",
    isOpen: true,
    rating: 4.7,
    reviews: 1200,
    tags: ["shopping", "mall", "clothes", "fashion", "shoes", "riverside mall", "retail"],
    services: ["140+ National retail stores", "Undercover parking", "Cinema complex", "Food court"]
  },

  // SERVICES - MBOMBELA & MPUMALANGA
  {
    id: "ser-mbombela-1",
    name: "24/7 Lowveld Locksmith & Security",
    category: "Services",
    description: "Emergency home & vehicle lockout service across Mbombela and White River. Transponder car key cutting and lock installation.",
    address: "45 Madiba Dr, Sonheuwel, Mbombela",
    area: "Mbombela (Nelspruit), Mpumalanga",
    baseDistance: 0.7,
    phone: "+27 82 899 4321",
    latitude: -25.4780,
    longitude: 30.9670,
    openingHours: "Open 24 Hours / 7 Days",
    isOpen: true,
    rating: 4.9,
    reviews: 210,
    tags: ["locksmith", "keys", "cut keys", "locked out", "lock replacement", "emergency locksmith", "car key", "lowveld locksmith"],
    services: ["24/7 Mobile emergency van dispatch", "Laser vehicle key programming", "Gate motor & lock repairs"]
  },
  {
    id: "ser-mbombela-2",
    name: "Plumber Pro Lowveld & Solar",
    category: "Services",
    description: "Licensed solar geysers, burst pipe repairs, high pressure drain unblocking, and certified plumbing installations.",
    address: "12 Waterfall Ave, Riverside Industrial, Mbombela",
    area: "Mbombela (Nelspruit), Mpumalanga",
    baseDistance: 1.3,
    phone: "+27 83 456 7890",
    latitude: -25.4420,
    longitude: 30.9650,
    openingHours: "Mon-Sun: 07:00 - 20:00",
    isOpen: true,
    rating: 4.8,
    reviews: 135,
    tags: ["plumber", "plumbing", "burst pipe", "leak", "geyser", "solar geyser", "drain", "handyman"],
    services: ["Geyser replacements with insurance cert", "Solar geyser conversion", "Drain camera inspection"]
  },

  // TRANSPORT - MBOMBELA & MPUMALANGA
  {
    id: "tra-mbombela-1",
    name: "Mbombela Central Transit & Bus Terminal",
    category: "Transport",
    description: "Central Lowveld public transport terminal connecting local minibus taxis, Buscor commuter buses, and intercity routes.",
    address: "Bester St & Henshall St, Mbombela CBD, Mbombela",
    area: "Mbombela (Nelspruit), Mpumalanga",
    baseDistance: 0.5,
    phone: "+27 13 755 8000",
    latitude: -25.4730,
    longitude: 30.9745,
    openingHours: "Mon-Sun: 05:00 - 21:00",
    isOpen: true,
    rating: 4.3,
    reviews: 420,
    tags: ["bus", "taxi rank", "transport", "buscor", "transit", "mbombela transport", "commute"],
    services: ["Buscor weekly & monthly tickets", "Regional taxi connections (White River, Barberton, Hazyview)", "City intercity coaches"]
  },

  // OTHER - MBOMBELA & MPUMALANGA
  {
    id: "oth-mbombela-1",
    name: "Lowveld National Botanical Garden",
    category: "Other",
    description: "Spectacular botanical sanctuary with scenic Crocodile River waterfalls, rainforest suspension bridge, indigenous flora, and tea garden.",
    address: "Madiba Dr, Riverside, Mbombela",
    area: "Mbombela (Nelspruit), Mpumalanga",
    baseDistance: 1.5,
    phone: "+27 13 752 5531",
    latitude: -25.4460,
    longitude: 30.9630,
    openingHours: "Mon-Sun: 08:00 - 18:00",
    isOpen: true,
    rating: 4.9,
    reviews: 890,
    tags: ["botanical garden", "nature", "park", "waterfalls", "tourist", "outdoor", "mbombela garden"],
    services: ["Botanical walking trails", "Red Leaf Tea Garden cafe", "Indigenous plant nursery"]
  }
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { AVAILABLE_AREAS, CITY_COORDINATES, CATEGORIES, PLACES_DATA };
}
